services:
  - type: web
    name: sekani-mall
    env: python
    buildCommand: "apt-get install -y python3-dev libjpeg-dev zlib1g-dev && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn sekani_mall.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: sekani-db
    databaseName: sekani_mall
    user: sekani_user
